- type: mock
  id: 0
  position: "somewhere over the rainbow"
  correction_offset: -2.0
  amplitude: 5
  mean: 20
  period: 30

- type: mock
  id: 1
  position: "behind the oven"
  correction_offset: 1.0
  amplitude: 10
  mean: 15
  period: 20
