- fall_below: 20
  sensor: 1
  sender: 'test@email.com'
  receiver: 'receiver@email.com'
  check_interval: 5
  message_subject: 'sensor fell below 20'
- rise_above: 20
  sensor: 1
  sender: 'test@email.com'
  receiver: 'receiver@email.com'
  check_interval: 5
  message_subject: 'sensor rose above 20'