- type: system_start
  sender: 'test@email.com'
  receiver: 'test2@email.com'
  message_subject: 'system started'
  check_interval: 5
- type: fall_below
  threshold: 20
  sensor: 1
  sender: 'test@email.com'
  receiver: 'test2@email.com'
  check_interval: 5
  message_subject: 'sensor fell below 20'
- type: rise_above
  threshold: 20
  sensor: 1
  sender: 'test@email.com'
  receiver: 'test2@email.com'
  check_interval: 5
  message_subject: 'sensor rose above 20'
  message: 'this is a message'